spring:
  # 设置spring boot上传文件大小限制
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: ${spring.application.name}

# actuator 监控
management:
  endpoint:
    health:
      show-details: always

jwt:
  expire: 2   # token有效时长, 单位小时
  token: token   # token 存在 cookie 中
  secret: 61D73234C4F93E03074D74D74D1E39D9