

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marcher-blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: AES@8TLqCgSLP/ldKx2xAGpTnw==
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # Redis
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      shutdown-timeout: 5000ms
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  cache:
    type: redis


cache:
  name: marcher
  expire-time: 180
  default-expire-time: 60

jwt:
  expire: 720   # token有效时长, 单位小时
  token: token   # token 存在 cookie 中
  secret: AES@u9bX3ohn2rEMj4pBh/SjSlVMbQ0piluFtz/LgHDtAG2O4BFU/QmgH1h1h2MVqAMI

oss:
  aliyunEndPoint: oss-cn-shenzhen.aliyuncs.com
  aliyunAccessKeyId: AES@IC1iNUMY0bxptfY/S+ckjI7gEVT9CaAfWHWHYxWoAwg=
  aliyunAccessKeySecret: AES@CPDzD4mKIroozQNzwGFNZ3QhlPo/VZXIfb5zIxp7pEQ=
  aliyunBucketName: marcher-temp
  aliyunRegion: https://marcher-temp.oss-cn-shenzhen.aliyuncs.com

#logging:
#  config: classpath:logback-dev.xml