spring:
  # 设置spring boot上传文件大小限制
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: ${spring.application.name}

# actuator 监控
management:
  endpoint:
    health:
      show-details: always


# swagger
swagger:
  enable: true
  group-name: apps-web
  title: pps-web
  description: pps-web
  version: 1.0.0
  contact-name: marcher